# Generated by Django 5.2.8 on 2025-11-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0002_alter_pais_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='capital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='poblacion',
            field=models.BigIntegerField(),
        ),
    ]
