# Generated by Django 5.2.8 on 2025-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_alter_pais_capital_alter_pais_poblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
